/**
 * Guards the bundled sample (public/samples/tour-du-mont-blanc-j1.gpx, generated by
 * scripts/gen-sample-gpx.mjs): it must stay parseable and realistic for a TMB stage 1.
 */
import { describe, expect, it } from 'vitest'
import sampleGpx from '../../public/samples/tour-du-mont-blanc-j1.gpx?raw'
import { parseGpx } from './gpx'

describe('sample tour-du-mont-blanc-j1.gpx', () => {
  const tracks = parseGpx(sampleGpx, 'tour-du-mont-blanc-j1.gpx')

  it('is a single realistic track from Les Houches to Les Contamines', () => {
    expect(tracks).toHaveLength(1)
    const track = tracks[0]
    expect(track.name).toMatch(/Mont-Blanc/)
    expect(track.segments).toHaveLength(1)
    const points = track.segments[0].points

    expect(points.length).toBeGreaterThanOrEqual(300)
    expect(points.length).toBeLessThanOrEqual(420)
    expect(points[0].lon).toBeCloseTo(6.7986, 2)
    expect(points[0].lat).toBeCloseTo(45.8911, 2)
    expect(points[points.length - 1].lon).toBeCloseTo(6.7273, 2)
    expect(points[points.length - 1].lat).toBeCloseTo(45.8225, 2)

    expect(track.stats.distanceM).toBeGreaterThan(15_000)
    expect(track.stats.distanceM).toBeLessThan(18_000)
    expect(track.stats.ascentM).toBeGreaterThan(650)
    expect(track.stats.ascentM).toBeLessThan(1000)
    expect(track.stats.descentM).toBeGreaterThan(450)
    expect(track.stats.minEle).toBeGreaterThan(950)
    expect(track.stats.maxEle).toBeGreaterThan(1640)
    expect(track.stats.maxEle).toBeLessThan(1700)
    expect(track.stats.startTime).toBe(Date.parse('2025-07-12T07:00:00Z'))
    expect(track.stats.durationS).toBeGreaterThan(4 * 3600)
    expect(track.stats.durationS).toBeLessThan(7 * 3600)
  })

  it('has monotonic times every ~60 s and a heart rate on every point', () => {
    const points = tracks[0].segments[0].points
    for (let i = 1; i < points.length; i++) {
      expect(points[i].time! - points[i - 1].time!).toBe(60_000)
    }
    for (const p of points) {
      expect(p.hr).toBeGreaterThanOrEqual(90)
      expect(p.hr).toBeLessThanOrEqual(150)
      expect(p.ele).toBeDefined()
    }
  })
})
