#!/usr/bin/env node
/**
 * Generates src/geo/egm96Grid.ts: the EGM96 geoid undulation N (metres, geoid above the WGS84 ellipsoid) on a 1° grid,
 * 181 rows (lat 90 → -90) × 360 columns (lon -180 → 179), Int16 little-endian centimetres, base64 (~170 KB).
 *
 * Source: NGA EGM96 15' grid as redistributed by PROJ-data, `us_nga_egm96_15.tif` (https://cdn.proj.org/), « Derived
 * from work by NGA. Public Domain ». Grid nodes on whole degrees are kept as is (every 4th node of the 15' grid).
 *
 * Usage: node scripts/gen-geoid.mjs [path/to/us_nga_egm96_15.tif]   (downloads it from cdn.proj.org when omitted)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { inflateSync } from 'node:zlib'

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), '../src/geo/egm96Grid.ts')
const URL_15 = 'https://cdn.proj.org/us_nga_egm96_15.tif'

const input = process.argv[2]
const buf = input ? readFileSync(input) : Buffer.from(await (await fetch(URL_15)).arrayBuffer())

// --- minimal TIFF reader: little-endian, one float32 band, tiled, deflate, floating-point predictor (3) ---
if (buf.toString('latin1', 0, 2) !== 'II' || buf.readUInt16LE(2) !== 42) throw new Error('expected a little-endian TIFF')
const tags = new Map()
const ifd = buf.readUInt32LE(4)
const SIZES = { 3: 2, 4: 4, 12: 8 }
for (let i = 0, n = buf.readUInt16LE(ifd); i < n; i++) {
  const e = ifd + 2 + i * 12
  const tag = buf.readUInt16LE(e)
  const type = buf.readUInt16LE(e + 2)
  const count = buf.readUInt32LE(e + 4)
  const size = SIZES[type]
  if (!size) continue
  const at = count * size <= 4 ? e + 8 : buf.readUInt32LE(e + 8)
  const values = []
  for (let k = 0; k < count; k++) {
    const p = at + k * size
    values.push(type === 3 ? buf.readUInt16LE(p) : type === 4 ? buf.readUInt32LE(p) : buf.readDoubleLE(p))
  }
  tags.set(tag, values)
}
const [width] = tags.get(256)
const [height] = tags.get(257)
const [tileW] = tags.get(322)
const [tileH] = tags.get(323)
if (tags.get(258)[0] !== 32 || tags.get(259)[0] !== 8 || tags.get(317)[0] !== 3) throw new Error('unexpected TIFF layout')
const [scaleX] = tags.get(33550)
const tie = tags.get(33922)
if (scaleX !== 0.25 || tie[3] !== -180 || tie[4] !== 90 || width !== 1440 || height !== 721) throw new Error('unexpected grid')

const grid = new Float32Array(width * height)
const offsets = tags.get(324)
const counts = tags.get(325)
const across = Math.ceil(width / tileW)
for (let t = 0; t < offsets.length; t++) {
  const raw = inflateSync(buf.subarray(offsets[t], offsets[t] + counts[t]))
  const tx = (t % across) * tileW
  const ty = Math.floor(t / across) * tileH
  const rowBytes = tileW * 4
  for (let r = 0; r < tileH; r++) {
    const row = raw.subarray(r * rowBytes, (r + 1) * rowBytes)
    // undo the byte-wise horizontal differencing, then the byte-plane shuffle (plane 0 = most significant byte)
    for (let i = 1; i < rowBytes; i++) row[i] = (row[i] + row[i - 1]) & 0xff
    const y = ty + r
    if (y >= height) break
    for (let c = 0; c < tileW && tx + c < width; c++) {
      const v = Buffer.from([row[c], row[tileW + c], row[2 * tileW + c], row[3 * tileW + c]]).readFloatBE(0)
      grid[y * width + tx + c] = v
    }
  }
}

// --- 1° subsample, Int16 cm ---
const ROWS = 181
const COLS = 360
const out = Buffer.alloc(ROWS * COLS * 2)
for (let r = 0; r < ROWS; r++) {
  for (let c = 0; c < COLS; c++) out.writeInt16LE(Math.round(grid[r * 4 * width + c * 4] * 100), (r * COLS + c) * 2)
}

writeFileSync(
  OUT,
  `/**
 * EGM96 geoid undulation on a 1° grid — generated by scripts/gen-geoid.mjs, do not edit.
 * Source: NGA EGM96 15' grid (PROJ-data \`us_nga_egm96_15.tif\`), public domain. ${ROWS} rows (lat 90 → -90) × ${COLS}
 * columns (lon -180 → 179), Int16 little-endian, centimetres, base64.
 */
export const EGM96_ROWS = ${ROWS}
export const EGM96_COLS = ${COLS}
export const EGM96_CM_BASE64 =
  '${out.toString('base64')}'
`,
)
console.log(`wrote ${OUT} (${ROWS}×${COLS}, ${out.length} bytes)`)
